config/routes.rb
DilIe::Application.routes.draw do
  resources :definitions
  resources :bibls
  resources :part_of_speeches
  resources :entries do
    post 'search', on: :collection 
  end
  resources :columns
  resources :lines

  match '/search' => 'entries#search', :as => :search, :via => :post
  match '/:id' => 'high_voltage/pages#show', :as => :static, :via => :get
  match '/browse' => 'columns#index', :as => :browse, :via => :get
  match '/bibliography' => 'bibls#index', :as => 'bibliography', :via => :get
  root :to => 'columns#show', :id => '1'
end

app/models/bibl.rb
class Bibl < ActiveRecord::Base
  has_many :references
  has_many :entries, through: :references
end

app/models/column.rb
class Column < ActiveRecord::Base
  has_many :lines
end

app/models/definition.rb
class Definition < ActiveRecord::Base
  belongs_to :entry
end

app/models/entries_part_of_speech.rb
class EntriesPartOfSpeech < ActiveRecord::Base
  belongs_to :entry
  belongs_to :part_of_speech
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  has_many :entries_part_of_speeches
  has_many :part_of_speeches, through: :entries_part_of_speeches
  has_many :references
  has_many :bibls, through: :references
  has_many :definitions
end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :column
end

app/models/part_of_speech.rb
class PartOfSpeech < ActiveRecord::Base
  has_many :entries_part_of_speeches
  has_many :entries, through: :entries_part_of_speeches
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  belongs_to :entry
  belongs_to :bibl
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bibls_controller.rb
class BiblsController < ApplicationController
  def index
    @bibls = Bibl.order(:str)
  end
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  def index
    @columns = Column.all
  end

  def show
    @column = Column.find(params[:id])
    @viewed = params[:id].to_i * 100 / Column.count
    begin
      @next_column = Column.find(params[:id].to_i + 1)
      @prev_column = Column.find(params[:id].to_i - 1)
    rescue
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
  end
  
  def search
    @entry = Entry.find_by_orth(params[:q])
    redirect_to @entry
  end

  def show
    @entry = Entry.find(params[:id])
    begin
      @next_entry = Entry.find(params[:id].to_i + 1)
      @prev_entry = Entry.find(params[:id].to_i - 1)
    rescue
    end
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bibls_helper.rb
module BiblsHelper
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/helpers/part_of_speeches_helper.rb
module PartOfSpeechesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{lang: :en}
  %head
    %meta{charset: "utf-8"}
    %title Dictionary of the Irish Language
    = csrf_meta_tags
    :plain
      <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
    = stylesheet_link_tag 'application', media: :all
    %link{href: "images/favicon.ico",                   rel: "shortcut icon"}
    %link{href: "images/apple-touch-icon.png",          rel: "apple-touch-icon"}
    %link{href: "images/apple-touch-icon-72x72.png",    rel: "apple-touch-icon", sizes: "72x72"}
    %link{href: "images/apple-touch-icon-114x114.png",  rel: "apple-touch-icon", sizes: "114x114"}
  %body
    %header
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.btn.btn-navbar{'data-target' => '.nav-collapse', 'data-toggle' => 'collapse'}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to 'Dictionary of the Irish Language', root_url, class: :brand
            %ul.nav
              %li= link_to 'About', page_path('about')
              %li= link_to 'Search', '/'
              %li= link_to 'Browse', browse_path
              %li= link_to 'Bibliography', bibls_url
              %li= link_to 'Contact', page_path('contact')
            = form_tag 'search', class: 'navbar-search pull-right' do
              %input.search-query.typeahead{:type => :text, :placeholder => "Search", :name => :q, 'data-provide' => :typeahead, 'data-items' => 7, 'data-source' => Entry.select(:orth).map(&:orth)}

    #site.container.container-fluid
      = yield
    %footer
      %p= raw "Copyright &copy; 2012 Queen's University, Belfast.  All Rights Reserved."
    = javascript_include_tag 'application'

app/views/pages/contact.html.haml
%h1 Contact